from selenium.webdriver.common.by import By


class Locator:
    ORDERS_HISTORY = (By.XPATH, "//a[contains(text(), 'История заказов')]")
    LOGOUT_BUTTON = (By.XPATH, "//button[text()='Выход']")
    RESET_BUTTON = (By.XPATH, "//button[text()='Восстановить']")
    FIX_PASSWORD = (By.XPATH, "//label[contains(text(), 'Введите код из письма')]")
    TOGGLE_ACTIVE = (By.CLASS_NAME, 'input_status_active')
    PERSON_CAB = (By.XPATH, "//p[text()='Личный Кабинет']")
    LOGIN_BUTTON = (By.XPATH, "//button[text()='Войти']")
    CREAT_ORDER = (By.XPATH, "//button[text()='Оформить заказ']")
    CLOSE_MODALE_WINDOW = (By.XPATH, "//button[contains(@class, 'Modal_modal__close_modified__3V5XS')]")
    INGREDIENT_CARD = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient')]")
    DETAILS_INGREDIENT = (By.XPATH, "//h2[text()='Детали ингредиента']")
    CONSTRUCTOR_BUTTON = (By.XPATH, "//p[text()='Конструктор']")
    LENT_ORDER = (By.XPATH, "//p[text()='Лента Заказов']")
    ORDER_BUTTON = (By.XPATH, "//a[contains(@class, 'OrderHistory_link__1iNby')]")
    TEXT_STRUCTURE = (By.XPATH, "//p[text()='Cостав']")
    INGREDIENT_ITEM = (By.XPATH, "//div[contains(@class, 'ingredient-item')]")
    CTREAT_ORDER_BUTTON = (By.XPATH, "//button[text()='Оформить заказ']")
    BUN_COUNTER = (By.XPATH, "//span[text()='Булки']/following-sibling::span")
    INGREDIENT_CARD_SWAP = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient')]")
    INGREDIENT_CARD_SWAP_GOAL = (By.XPATH, "//div[contains(@class, 'constructor-element')]")
    ORDER_ITEM = (By.XPATH, "//div[contains(@class, 'order-item')]")
    TOTAL_ORDERS_COUNTER = (By.XPATH, "//p[text()='Выполнено за все время:']/following-sibling::p[1]")
    TODAY_ORDERS_COUNTER = (By.XPATH, "//p[text()='Выполнено за сегодня:']/following-sibling::p[1]")
    IN_PROGRESS_ORDERS = (By.XPATH, "//p[text()='В работе']")
    EMAIL_INPUT = (By.XPATH, "//input[@name='name']")
    PASSWORD_INPUT = (By.XPATH, "//input[@type='password']")
    FORGOT_PASSWORD_LINK = (By.XPATH, "//a[text()='Восстановить пароль']")
    MODAL_OVERLAY = (By.XPATH, "//div[contains(@class, 'Modal_modal__container__Wo2l_')]")
    RESET_EMAIL_INPUT = (By.XPATH, "//input[@name='name']")
    SHOW_PASSWORD_BUTTON = (By.XPATH, "//div[contains(@class, 'input__icon')]")
    NUMBDER_LENT_ORDER = (By.XPATH, "//p[contains(@class, 'text_type_digits-default')]")
    TOTAL_ORDERS_COUNTER_TEXT = (By.XPATH, "//p[text()='Выполнено за все время:']")
    COUNTER_COUNT = (By.XPATH, "//p[contains(@class, 'counter_counter__num__3nue1')]")
    CREAT_BURGER_TEXT = (By.XPATH, "//h1[text()='Соберите бургер']")
    STARTED_PREPARING_ORDER = (By.XPATH, "//p[text()='Ваш заказ начали готовить']")
    KOD_FROM_MESSAGE = (By.XPATH, "//label[text()='Введите код из письма']")
    PASSWORD_FORGOT_TYPE_PASSWORD = (By.XPATH, "//input[@type='password']")
    PASSWORD_FORGOT_TYPE_TEXT = (By.XPATH, "//input[@type='text']")
    PASSWORD_FORGOT_NAME = (By.NAME, "Введите новый пароль")
    ORDERS_NUMBER_OF_MODAL = (By.XPATH, "//h2[contains(@class, 'Modal_modal__title__2L34m') and contains(@class, 'text_type_digits-large')]")
    ORDERS_NUMBER_OF_HISTORY = (By.XPATH, "//p[contains(@class, 'text_type_digits-default')]")
    COMPLETED_ORDER_TEXT = (By.XPATH, "//P[text()='Выполнен']")
    IN_WORK = (By.XPATH, "//li[contains(@class, 'text')]")


